version: "3.4"

services:
  app-web:
    build:
      context: ./
      dockerfile: ./deployments/app.Dockerfile
      target: app
    networks:
      - application
    command:
      - "web"
    ports:
      - "8080:8080"
    expose:
      - 8080
    tty: true
  app-daemon:
    build:
      context: ./
      dockerfile: ./deployments/app.Dockerfile
      target: app
    networks:
      - application
    command:
      - "daemon"
    tty: true
networks:
  application:
    driver: bridge