# example file https://github.com/prometheus/prometheus/blob/release-3.1/config/testdata/conf.good.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
#  Добавляем дополнительный лейбл для всех метрик
  external_labels:
    monitor: 'go-template'
rule_files:
  - 'prometheus.rules.yml'
scrape_configs:
  - job_name: "node"
#    Переопределяем время сбора метрик для данной конфигурации
    scrape_interval: 5s
    static_configs:
      - targets: [ "localhost:9100" ]
  - job_name: "app"
    static_configs:
      - targets: [ "localhost:8081" ]
